src/mapping.jl

Code block was at the wrong place.

moved colormaps outside of if statement

---

src/analysis.jl
src/biascorrect.jl
src/extract.jl
src/functions.jl
src/heatsum_indices.jl
src/indices.jl
src/interface.jl
src/mapping.jl
test/biascorrect_test.jl
test/indices_test.jl
test/interface_test.jl

Modifications for data dimensions. Time dimensions is now the last dimension.

Permutedims

---

src/mapping.jl
test/mapping_test.jl

New projections:
- "Arctic"/"Antarctic" Polar Stereographic (aps, aaps)
- "SouthAmerica" Lambert Conformal Conic (sa)
Still need to add a few tests as well as update api/docs.

More Projections

---

src/ClimateTools.jl
src/extract.jl
src/functions.jl
src/indicators.jl
src/mapping.jl
test/mapping_test.jl

Fonction pour le calcul de la pression de vapeur à partir de données de la pression de surface et l'humidité spécifique.
**Notes 1** : non testée
**Notes 2** : méthode pour construire ClimGrid à revoir?

Vp calculation

---

src/ClimateTools.jl
src/biascorrect.jl
test/biascorrect_test.jl

Fonction semble fonctionnée, avec test simple. Il resterait à déterminer comment définir la fonction de transfert lorqu'il y a trop de NaN.

Func qqmaptf

---

src/biascorrect.jl
test/biascorrect_test.jl

Tu peux supprimer la branche après le merge.
Les fonctions qqmaptf et qqmap(fut, ITP) sont maintenant calculées sur plusieurs threads. C'était déjà rapide, maintenant, c'est presque instantané (durant les tests).

parallel processing qqmaptf() and qqmap()

---

src/ClimateTools.jl
src/biascorrect.jl
src/indicators.jl
test/indicators_test.jl

Modification du calcul wbgt pour prendre la température moyenne plutôt que la température durant la journée et ajout de la fonction pour calculer la température moyenne.

Meantemperature

---

src/biascorrect.jl

modification pour tenir compte des index "k" non-hardcodé

fixed k-index for leapyears in corrjuliandays

---

src/indicators.jl

Juste une petite modification pour pouvoir calculer le wbgt avec différente mesure de température

Allow wbgt() to take tasmax and tasmin

---

src/biascorrect.jl

Ça accélère les fonctions polyval et polyfit d'un facteur de 2

parrallel polyval and polyfit

---

src/mapping.jl

1) Ajout de l'option de définir le colorscale
2) Ajout des variables wbgtmean, wbgtmax, vp dans la boucle conditionnelle
Ça semble fonctionner

modify colorscale

---

src/biascorrect.jl
src/extract.jl
test/biascorrect_test.jl
test/interface_test.jl

Bug when using multiplicative method

fixed multiplicative method

---

.travis.yml
REQUIRE
appveyor.yml
deps/build.jl
docs/make.jl

Trying to defer python dependency into a build script.

Build script

---

REQUIRE
src/biascorrect.jl
src/time.jl

This fixes a bug found in daymean. Should be more robust!

Daymean fix

---

deps/build.jl
docs/make.jl
src/time.jl

Generalized day functions (daymean and daysum). Also multi-threaded the loops for those functions. Faster than ever!

Daymean gen

---

REQUIRE
src/ClimateTools.jl
src/analysis.jl
src/biascorrect.jl
src/export.jl
src/extract.jl
src/functions.jl
src/indicators.jl
src/indices.jl
src/interface.jl
src/mapping.jl
src/time.jl
test/indices_test.jl
test/interface_test.jl
test/mapping_test.jl
test/runtests.jl

Some optimizations with in-place operations

Optimize bc

---

src/ClimateTools.jl
src/mapping.jl
test/extract_test.jl
test/mapping_test.jl

* histogram method
* more tests on `write` function for non-regular grids

added histogram

---

LICENSE.md
REQUIRE
src/ClimateTools.jl
src/extract.jl
src/functions.jl
src/indicators.jl
src/mapping.jl
src/time.jl

Drought isc

---

src/mapping.jl
src/time.jl

Removing unneccessary functions

---

src/extract.jl
src/mapping.jl
test/mapping_test.jl

Fix datasets that does not contains "grid_mapping" attributes in the variable's attribute.

improved detection of grid types + africa maps

---

README.md
src/extract.jl

Fixing #103

---

src/biascorrect.jl

Fixes bug for 0-bounded variables for bias correction function.

fixed prec qqmap bug for 0 values

---

src/ClimateTools.jl
src/extract.jl

This is a partial fix for https://github.com/JuliaClimate/ClimateTools.jl/issues/135 which I feel could be useful to merge at this point. Eventually it would be replaced with a more general solution though.

support more dimension / variable names
